spring:
  main:
    banner-mode: "off"
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
server:
  port: 8080
weather:
  base-url: https://api.openweathermap.org/data/2.5/